import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// app/layout.tsx
// src/app/layout.tsx
// src/app/layout.tsx
import './globals.css';
import NavBar from './components/NavBar'; // Asegúrate de importar tu NavBar

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <head>
        <title>Mi Aplicación</title>
      </head>
      <body className="flex">
        <NavBar /> {/* Asegúrate de que la barra de navegación esté aquí */}
        <div className="flex-1">{children}</div> {/* Contenido principal */}
      </body>
    </html>
  );
}

